tex = input('Digite algo: ')
print('O tipo primitivo desse valor é',type(tex))
print('Só tem espaços?',tex.isspace())
print('É um número?',tex.isnumeric())
print('É alfabético?',tex.isalpha())
print('É alfanumérico?',tex.isalnum())
print('Está em maiúsculas?',tex.isupper())
print('Está em minúsculas?',tex.islower())
print('Está capitalizada?',tex.istitle())